### ISSUE TITLE
Add version support to package and imports

### ISSUE THREAD

**Issue by bsenduran** [ballerinalang/ballerina#500] opened 2017-01-04 09:57 UTC
sample grammar with hard coded version
```
packageDeclaration
    :   'package' packageName ('version' '1.0')? ';'
    ;

importDeclaration
    :   'import' packageName ('version' '1.0')? ('as' Identifier)? ';'
    ;
```

**Comment by SupunS** [comment] 2017-11-27 12:52
duplicate of https://github.com/ballerinalang/ballerina/issues/4087

**Closed by SupunS** 2017-11-27 12:52 UTC
Labels: Type/Improvement
