### ISSUE TITLE
http ClientConnector fails to find route to host, ballerina never sends a response

### ISSUE THREAD

**Issue by gludington** [ballerinalang/ballerina#2408] opened 2017-05-24 16:51 UTC
Related to #2393 , but with details specific to this case

This occurs with some links, but not others, and at least one API works when running 0.87 but not when running 0.88-SNAPSHOT.

Using this ballerina service:
```
import ballerina.net.http;
@http:BasePath{value: "/chuck"}
service chuck {
    http:ClientConnector chuckService = create http:ClientConnector("https://api.chucknorris.io/jokes/random");

    @http:GET{}
    @http:Path{value: "/"}
    resource productsInfo(message m) {
        message response = http:ClientConnector.get(chuckService, "/", m);

        reply response;
    }
}
```
The request to /chuck/ never returns.

on OSX, the behavior is reproducible running 0.88-SNAPSHOT inside IntelliJ, running 0.87 from the composer, or running 0.87 ballerina run service /path/to/chuck.val from the command line.

The error log shows that a route to the host cannot be established, though browsers and curl on the same host have no issues hitting this URL.  The behavior is reproducible with other URLs, as well, such as:

- http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1
- https://graph.facebook.com/cnn (this one works on 0.87, but not on 0.88-SNAPSHOT)

```
error in ballerina program: failed to invoke 'get' action in ClientConnector. Error when creating channel for route api.chucknorris.io-443
	 at ballerina.net.http:get(chuck.bal:10)
	 at productsInfo(chuck.bal:7)
	 at .:chuck(chuck.bal:4)

Exception in thread "BLangWorker-1" org.ballerinalang.util.exceptions.BallerinaException: Cannot handle error using the error handler for: https
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:136)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:100)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: error in ballerina program: failed to invoke 'get' action in ClientConnector. Error when creating channel for route api.chucknorris.io-443
	at org.ballerinalang.services.DefaultServerConnectorErrorHandler.handleError(DefaultServerConnectorErrorHandler.java:45)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:134)
	... 5 more
Caused by: org.ballerinalang.util.exceptions.BallerinaException: error in ballerina program: failed to invoke 'get' action in ClientConnector. Error when creating channel for route api.chucknorris.io-443
	... 6 more
```

**Comment by djkevincr** [comment] 2017-05-25 04:01
@gludington We are currently looking into the issue, will update you with the progress.

**Comment by deQuota** [comment] 2017-07-19 12:08
Any improvements for this issue and issue #2393. Is there any other way to retrieve jsons from services?

**Comment by pubudu91** [comment] 2017-08-31 06:23
The example given in the issue is outdated. However, I modified it as given below and it works fine as of v0.93
```
import ballerina.net.http;
@http:configuration{basePath: "/chuck"}
service<http> chuck {
    http:ClientConnector chuckService = create http:ClientConnector("https://api.chucknorris.io/jokes/random");

    @http:resourceConfig {
        path: "/",
        methods: ["GET"]
    }
    resource productsInfo(message m) {
        message response = chuckService.get("", m);

        reply response;
    }
}
```
Note that I have passed an empty string as the path. A '/' would work here as well. However in this particular example, if the path is `https://api.chucknorris.io/jokes/random/`, a 404 is returned, hence the omission of the '/'.

**Comment by shafreenAnfar** [comment] 2017-10-17 17:33
As this has been fixed in the latest version, I am closing the issue.

**Closed by shafreenAnfar** 2017-10-17 17:33 UTC
