### ISSUE TITLE
Cannot obtain attribute value for given payload when the xml@[] is used with namespaces

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2901] opened 2017-07-13 04:50 UTC
This issue is based on [1] 

**Payload**
```
<?xml version="1.0" encoding="UTF-8"?>
 <cre:InputParameters  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">
    	<cre:P_API_VERSION_NUMBER>1.0</cre:P_API_VERSION_NUMBER>
		<cre:P_INIT_MSG_LIST>T</cre:P_INIT_MSG_LIST>
 	   <cre:P_COMMIT>F</cre:P_COMMIT>
		<cre:P_VALIDATION_LEVEL>100</cre:P_VALIDATION_LEVEL>
       <cre:P_SDR_HDR_REC>
        	<cre:REQUEST_NUMBER>SDR-CREATE-BPEL1</cre:REQUEST_NUMBER>
        	<cre:REQUEST_START_DATE>2008-08-18T12:00:00</cre:REQUEST_START_DATE>
  		  	<cre:REQUEST_END_DATE>2008-10-18T12:00:00</cre:REQUEST_END_DATE>>
        	<cre:USER_STATUS_ID>1701</cre:USER_STATUS_ID>
        	<cre:REQUEST_OUTCOME>IN_PROGRESS</cre:REQUEST_OUTCOME>
        	<cre:REQUEST_CURRENCY_CODE>USD</cre:REQUEST_CURRENCY_CODE>
        	<cre:SUPPLIER_ID>601</cre:SUPPLIER_ID>
       		<cre:SUPPLIER_SITE_ID>1415</cre:SUPPLIER_SITE_ID>
        	<cre:REQUESTOR_ID>100001499</cre:REQUESTOR_ID>
		  		<cre:ASSIGNEE_RESOURCE_ID>100001499</cre:ASSIGNEE_RESOURCE_ID>
		  		<cre:ORG_ID>204</cre:ORG_ID>
		  		<cre:ACCRUAL_TYPE>SUPPLIER</cre:ACCRUAL_TYPE>
		  		<cre:REQUEST_DESCRIPTION>Create</cre:REQUEST_DESCRIPTION>
       		<cre:SUPPLIER_CONTACT_EMAIL_ADDRESS>sdr.supplier@example.com</cre:SUPPLIER_CONTACT_EMAIL_ADDRESS>
       		<cre:SUPPLIER_CONTACT_PHONE_NUMBER>2255</cre:SUPPLIER_CONTACT_PHONE_NUMBER>
   	 		<cre:REQUEST_TYPE_SETUP_ID>400</cre:REQUEST_TYPE_SETUP_ID>
       		<cre:REQUEST_BASIS>Y</cre:REQUEST_BASIS>
       		<cre:USER_ID>1002795</cre:USER_ID>
   </cre:P_SDR_HDR_REC>
   <cre:P_SDR_LINES_TBL>
     		<cre:P_SDR_LINES_TBL_ITEM cre:line="true">
      				<cre:PRODUCT_CONTEXT>PRODUCT</cre:PRODUCT_CONTEXT>
						<cre:INVENTORY_ITEM_ID>2155</cre:INVENTORY_ITEM_ID>
						<cre:ITEM_UOM>Ea</cre:ITEM_UOM>
						<cre:REQUESTED_DISCOUNT_TYPE>%</cre:REQUESTED_DISCOUNT_TYPE>
						<cre:REQUESTED_DISCOUNT_VALUE>20</cre:REQUESTED_DISCOUNT_VALUE>
						<cre:COST_BASIS>200</cre:COST_BASIS>
						<cre:MAX_QTY>200</cre:MAX_QTY>
						<cre:APPROVED_DISCOUNT_TYPE>%</cre:APPROVED_DISCOUNT_TYPE>
						<cre:APPROVED_DISCOUNT_VALUE>20</cre:APPROVED_DISCOUNT_VALUE>
						<cre:APPROVED_MAX_QTY>200</cre:APPROVED_MAX_QTY>
						<cre:VENDOR_APPROVED_FLAG>Y</cre:VENDOR_APPROVED_FLAG>
						<cre:PRODUCT_COST_CURRENCY>USD</cre:PRODUCT_COST_CURRENCY>
						<cre:END_CUSTOMER_CURRENCY>USD</cre:END_CUSTOMER_CURRENCY>
         </cre:P_SDR_LINES_TBL_ITEM>
      </cre:P_SDR_LINES_TBL>
   <cre:P_SDR_CUST_TBL>
			<cre:P_SDR_CUST_TBL_ITEM cre:line="false">
						<cre:CUST_ACCOUNT_ID>1290</cre:CUST_ACCOUNT_ID>
						<cre:PARTY_ID>1290</cre:PARTY_ID>
						<cre:SITE_USE_ID>10479</cre:SITE_USE_ID>
						<cre:CUST_USAGE_CODE>BILL_TO</cre:CUST_USAGE_CODE>
						<cre:END_CUSTOMER_FLAG>N</cre:END_CUSTOMER_FLAG>     
      </cre:P_SDR_CUST_TBL_ITEM>
         <cre:P_SDR_CUST_TBL_ITEM cre:line="true">
						<cre:CUST_ACCOUNT_ID>1287</cre:CUST_ACCOUNT_ID>
						<cre:PARTY_ID>1287</cre:PARTY_ID>
						<cre:SITE_USE_ID>1418</cre:SITE_USE_ID>
						<cre:CUST_USAGE_CODE>CUSTOMER</cre:CUST_USAGE_CODE>
						<cre:END_CUSTOMER_FLAG>Y</cre:END_CUSTOMER_FLAG>     
      </cre:P_SDR_CUST_TBL_ITEM>
  </cre:P_SDR_CUST_TBL>
</cre:InputParameters>
```
**Source**
```
function getAttributeFromPayload(xml value)(string){
    xml firstLevelChild = xmls:children(value);
    system:println(firstLevelChild);
    system:println(".....................");
    xml specificChild = xmls:select(firstLevelChild, "{http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/}P_SDR_LINES_TBL");
    system:println(specificChild);
    system:println("......................");
    xml childrenOfSpecificChild = xmls:children(specificChild);
    system:println(childrenOfSpecificChild);
    system:println(".......................");
    xml specificSecondLevelChild = xmls:select(childrenOfSpecificChild, "{http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/}P_SDR_LINES_TBL_ITEM");
    system:println(specificSecondLevelChild);
    system:println(".......................");
    system:println(specificSecondLevelChild@);
    return specificSecondLevelChild@["{http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/}line"];
}
```

**Console output**

```
    	<cre:P_API_VERSION_NUMBER xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">1.0</cre:P_API_VERSION_NUMBER>
		<cre:P_INIT_MSG_LIST xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">T</cre:P_INIT_MSG_LIST>
 	   <cre:P_COMMIT xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">F</cre:P_COMMIT>
		<cre:P_VALIDATION_LEVEL xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">100</cre:P_VALIDATION_LEVEL>
       <cre:P_SDR_HDR_REC xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">
        	<cre:REQUEST_NUMBER>SDR-CREATE-BPEL1</cre:REQUEST_NUMBER>
        	<cre:REQUEST_START_DATE>2008-08-18T12:00:00</cre:REQUEST_START_DATE>
  		  	<cre:REQUEST_END_DATE>2008-10-18T12:00:00</cre:REQUEST_END_DATE>&gt;
        	<cre:USER_STATUS_ID>1701</cre:USER_STATUS_ID>
        	<cre:REQUEST_OUTCOME>IN_PROGRESS</cre:REQUEST_OUTCOME>
        	<cre:REQUEST_CURRENCY_CODE>USD</cre:REQUEST_CURRENCY_CODE>
        	<cre:SUPPLIER_ID>601</cre:SUPPLIER_ID>
       		<cre:SUPPLIER_SITE_ID>1415</cre:SUPPLIER_SITE_ID>
        	<cre:REQUESTOR_ID>100001499</cre:REQUESTOR_ID>
		  		<cre:ASSIGNEE_RESOURCE_ID>100001499</cre:ASSIGNEE_RESOURCE_ID>
		  		<cre:ORG_ID>204</cre:ORG_ID>
		  		<cre:ACCRUAL_TYPE>SUPPLIER</cre:ACCRUAL_TYPE>
		  		<cre:REQUEST_DESCRIPTION>Create</cre:REQUEST_DESCRIPTION>
       		<cre:SUPPLIER_CONTACT_EMAIL_ADDRESS>sdr.supplier@example.com</cre:SUPPLIER_CONTACT_EMAIL_ADDRESS>
       		<cre:SUPPLIER_CONTACT_PHONE_NUMBER>2255</cre:SUPPLIER_CONTACT_PHONE_NUMBER>
   	 		<cre:REQUEST_TYPE_SETUP_ID>400</cre:REQUEST_TYPE_SETUP_ID>
       		<cre:REQUEST_BASIS>Y</cre:REQUEST_BASIS>
       		<cre:USER_ID>1002795</cre:USER_ID>
   </cre:P_SDR_HDR_REC>
   <cre:P_SDR_LINES_TBL xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">
     		<cre:P_SDR_LINES_TBL_ITEM cre:line="true">
      				<cre:PRODUCT_CONTEXT>PRODUCT</cre:PRODUCT_CONTEXT>
						<cre:INVENTORY_ITEM_ID>2155</cre:INVENTORY_ITEM_ID>
						<cre:ITEM_UOM>Ea</cre:ITEM_UOM>
						<cre:REQUESTED_DISCOUNT_TYPE>%</cre:REQUESTED_DISCOUNT_TYPE>
						<cre:REQUESTED_DISCOUNT_VALUE>20</cre:REQUESTED_DISCOUNT_VALUE>
						<cre:COST_BASIS>200</cre:COST_BASIS>
						<cre:MAX_QTY>200</cre:MAX_QTY>
						<cre:APPROVED_DISCOUNT_TYPE>%</cre:APPROVED_DISCOUNT_TYPE>
						<cre:APPROVED_DISCOUNT_VALUE>20</cre:APPROVED_DISCOUNT_VALUE>
						<cre:APPROVED_MAX_QTY>200</cre:APPROVED_MAX_QTY>
						<cre:VENDOR_APPROVED_FLAG>Y</cre:VENDOR_APPROVED_FLAG>
						<cre:PRODUCT_COST_CURRENCY>USD</cre:PRODUCT_COST_CURRENCY>
						<cre:END_CUSTOMER_CURRENCY>USD</cre:END_CUSTOMER_CURRENCY>
         </cre:P_SDR_LINES_TBL_ITEM>
      </cre:P_SDR_LINES_TBL>
   <cre:P_SDR_CUST_TBL xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">
			<cre:P_SDR_CUST_TBL_ITEM cre:line="false">
						<cre:CUST_ACCOUNT_ID>1290</cre:CUST_ACCOUNT_ID>
						<cre:PARTY_ID>1290</cre:PARTY_ID>
						<cre:SITE_USE_ID>10479</cre:SITE_USE_ID>
						<cre:CUST_USAGE_CODE>BILL_TO</cre:CUST_USAGE_CODE>
						<cre:END_CUSTOMER_FLAG>N</cre:END_CUSTOMER_FLAG>     
      </cre:P_SDR_CUST_TBL_ITEM>
         <cre:P_SDR_CUST_TBL_ITEM cre:line="true">
						<cre:CUST_ACCOUNT_ID>1287</cre:CUST_ACCOUNT_ID>
						<cre:PARTY_ID>1287</cre:PARTY_ID>
						<cre:SITE_USE_ID>1418</cre:SITE_USE_ID>
						<cre:CUST_USAGE_CODE>CUSTOMER</cre:CUST_USAGE_CODE>
						<cre:END_CUSTOMER_FLAG>Y</cre:END_CUSTOMER_FLAG>     
      </cre:P_SDR_CUST_TBL_ITEM>
  </cre:P_SDR_CUST_TBL>

.....................
<cre:P_SDR_LINES_TBL xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/">
     		<cre:P_SDR_LINES_TBL_ITEM cre:line="true">
      				<cre:PRODUCT_CONTEXT>PRODUCT</cre:PRODUCT_CONTEXT>
						<cre:INVENTORY_ITEM_ID>2155</cre:INVENTORY_ITEM_ID>
						<cre:ITEM_UOM>Ea</cre:ITEM_UOM>
						<cre:REQUESTED_DISCOUNT_TYPE>%</cre:REQUESTED_DISCOUNT_TYPE>
						<cre:REQUESTED_DISCOUNT_VALUE>20</cre:REQUESTED_DISCOUNT_VALUE>
						<cre:COST_BASIS>200</cre:COST_BASIS>
						<cre:MAX_QTY>200</cre:MAX_QTY>
						<cre:APPROVED_DISCOUNT_TYPE>%</cre:APPROVED_DISCOUNT_TYPE>
						<cre:APPROVED_DISCOUNT_VALUE>20</cre:APPROVED_DISCOUNT_VALUE>
						<cre:APPROVED_MAX_QTY>200</cre:APPROVED_MAX_QTY>
						<cre:VENDOR_APPROVED_FLAG>Y</cre:VENDOR_APPROVED_FLAG>
						<cre:PRODUCT_COST_CURRENCY>USD</cre:PRODUCT_COST_CURRENCY>
						<cre:END_CUSTOMER_CURRENCY>USD</cre:END_CUSTOMER_CURRENCY>
         </cre:P_SDR_LINES_TBL_ITEM>
      </cre:P_SDR_LINES_TBL>
......................

     		<cre:P_SDR_LINES_TBL_ITEM xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/" cre:line="true">
      				<cre:PRODUCT_CONTEXT>PRODUCT</cre:PRODUCT_CONTEXT>
						<cre:INVENTORY_ITEM_ID>2155</cre:INVENTORY_ITEM_ID>
						<cre:ITEM_UOM>Ea</cre:ITEM_UOM>
						<cre:REQUESTED_DISCOUNT_TYPE>%</cre:REQUESTED_DISCOUNT_TYPE>
						<cre:REQUESTED_DISCOUNT_VALUE>20</cre:REQUESTED_DISCOUNT_VALUE>
						<cre:COST_BASIS>200</cre:COST_BASIS>
						<cre:MAX_QTY>200</cre:MAX_QTY>
						<cre:APPROVED_DISCOUNT_TYPE>%</cre:APPROVED_DISCOUNT_TYPE>
						<cre:APPROVED_DISCOUNT_VALUE>20</cre:APPROVED_DISCOUNT_VALUE>
						<cre:APPROVED_MAX_QTY>200</cre:APPROVED_MAX_QTY>
						<cre:VENDOR_APPROVED_FLAG>Y</cre:VENDOR_APPROVED_FLAG>
						<cre:PRODUCT_COST_CURRENCY>USD</cre:PRODUCT_COST_CURRENCY>
						<cre:END_CUSTOMER_CURRENCY>USD</cre:END_CUSTOMER_CURRENCY>
         </cre:P_SDR_LINES_TBL_ITEM>
      
.......................
<cre:P_SDR_LINES_TBL_ITEM xmlns:cre="http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/" cre:line="true">
      				<cre:PRODUCT_CONTEXT>PRODUCT</cre:PRODUCT_CONTEXT>
						<cre:INVENTORY_ITEM_ID>2155</cre:INVENTORY_ITEM_ID>
						<cre:ITEM_UOM>Ea</cre:ITEM_UOM>
						<cre:REQUESTED_DISCOUNT_TYPE>%</cre:REQUESTED_DISCOUNT_TYPE>
						<cre:REQUESTED_DISCOUNT_VALUE>20</cre:REQUESTED_DISCOUNT_VALUE>
						<cre:COST_BASIS>200</cre:COST_BASIS>
						<cre:MAX_QTY>200</cre:MAX_QTY>
						<cre:APPROVED_DISCOUNT_TYPE>%</cre:APPROVED_DISCOUNT_TYPE>
						<cre:APPROVED_DISCOUNT_VALUE>20</cre:APPROVED_DISCOUNT_VALUE>
						<cre:APPROVED_MAX_QTY>200</cre:APPROVED_MAX_QTY>
						<cre:VENDOR_APPROVED_FLAG>Y</cre:VENDOR_APPROVED_FLAG>
						<cre:PRODUCT_COST_CURRENCY>USD</cre:PRODUCT_COST_CURRENCY>
						<cre:END_CUSTOMER_CURRENCY>USD</cre:END_CUSTOMER_CURRENCY>
         </cre:P_SDR_LINES_TBL_ITEM>
.......................
{"{http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/}line":"true"}

```

[1] https://github.com/ballerinalang/ballerina/pull/2768

**Comment by SupunS** [comment] 2017-07-26 16:26
Couldn't reproduce in v0.90.
In the above sample, value for `specificSecondLevelChild@["{http://xmlns.oracle.com/apps/ozf/soaprovider/plsql/ozf_sd_request_pub/create_sd_request/}line"]` was return as `true`, which is the correct behavior.

Hence closing the issue. Please reopen if the issue encountered again.

**Closed by SupunS** 2017-07-26 16:26 UTC
Labels: bug
