### ISSUE TITLE
SQL Connection created and returned from a function doesn't work

### ISSUE THREAD

**Issue by saadsahibjan** [ballerinalang/ballerina#3029] opened 2017-07-22 10:39 UTC
I created two functions in a file named 'DatabaseConnector.bal'

```
package db;

import ballerina.data.sql;

function createDbConnection()(sql:ClientConnector dbConnector) {
 map dbProperties = {"jdbcUrl":"jdbc:mysql://localhost:3306/oxygeon?useSSL=false","username":"root","password":""};
 dbConnector = create sql:ClientConnector(dbProperties);
 return dbConnector;
}

function closeDbConnection(sql:ClientConnector dbConnector) {
 sql:ClientConnector.close(dbConnector);
}
```

I used the 'dbConnector' which is returned from the 'createDbConnection()' function in a service which is in another .bal file but within the same package. But I get errors when i do any of the SQL operations using the 'dbConnector' which is returned from 'createDbConnection()'. 

But if I do the SQL connection within the service it self and do SQL operation it works fine. I don't find any reasons why SQL operations are not working when a db connection object is used which is created in a separated function. (note: function gets invoked.)

**Comment by erandidesilva** [comment] 2017-07-22 10:59
Can you please provide the code which invokes the createDbConnection function?

**Comment by saadsahibjan** [comment] 2017-07-22 11:32
```
package db;
  
import ballerina.net.http;
import ballerina.data.sql;
import ballerina.lang.messages;
import ballerina.lang.jsons;
import ballerina.lang.errors;

@http:configuration{basePath:"/db"}
service<http> CustomerMgtService {

	@http:POST{}
	@http:Path {value:"/frequency"}
	resource insertFrequency(message m) {
	 
		json payload = messages:getJsonPayload(m);
		int mobile = jsons:getInt(payload, "$.mobileNo");
		string categoryId = jsons:getString(payload, "$.catId");
		float time = jsons:getFloat(payload, "$.timeFrequency");
		sql:Parameter mobileNo = {sqlType:"integer",value:mobile};
		sql:Parameter catId = {sqlType:"varchar",value:categoryId};
		sql:Parameter timeFrequency = {sqlType:"float",value:time};
		sql:Parameter[] params = [mobileNo, catId, timeFrequency];
		string query = "Insert into frequency values (?,?,?)";
		 sql:ClientConnector dbConnector = createDbConnection();
		try {
		 sql:ClientConnector.update(dbConnector, query, params);
		} catch(errors:Error er) {
		 throw er;
		}
		closeDbConnection(dbConnector);
		message response = {};
		reply response;
	}
}
```

createDbConnection() and closeDbConnection(dbConnector) are the two functions and .bal files are within the same package

**Comment by anupama-pathirage** [comment] 2017-08-10 11:56
Duplicate of #3134

**Closed** 2017-08-10 11:56 UTC
Labels: duplicate
