### ISSUE TITLE
Invalid request message framing results in http 500 not http 400

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3120] opened 2017-08-08 13:07 UTC
**Request details**
Content-type: application/json
Payload: xml

In the above scenario since the content-type and the payload content is mismatching, ideally according to [1] 400 Bad Request should be sent.

**Comment by pubudu91** [comment] 2017-08-15 06:28
Can you please provide the source code which caused this as well? I tried this and got a 200 response.

**Comment by anupama-pathirage** [comment] 2017-11-08 12:39
@erandidesilva can you please provide a sample code to reproduce the issue

**Comment by erandidesilva** [comment] 2017-11-08 13:05
Sample
```
import ballerina.net.http;
@http:configuration {
    basePath:"/test"
}
service<http> service1 {
    resource echo1 (http:Request req,http:Response res) {
        var var1 = req.getJsonPayload();
        res.setJsonPayload(var1);
        res.send();
    }
}
```
```
Payload -> xml
Content-Type: application/json
```
This generates the following error which is printed to the console

```
error, message: error while retrieving json payload from message: failed to create json: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.wso2.carbon.transport.http.netty.message.HttpMessageDataStreamer$ByteBufferInputStream@aa08708; line: 1, column: 2]
	at ballerina.net.http:ballerina.net.http:Request.getJsonPayload(<native>:0)
	at .:service1.echo1(/home/erandi/ballerina_0.9/composerTest/Test.bal:7)
```
But the client is not getting anything except the code 500. SInce this is a bad request, this issue is to suggest a more informative code to point out the error.

**Comment by pubudu91** [comment] 2017-11-13 06:28
The output in the above sample is the expected behaviour. The above scenario is a mix of a limitation in Ballerina + programmer error. The limitation is that the `getJsonPayload()` function does not return any errors. Ideally, it should return an error if payload parsing fails and the user should then be able to look at the error and handle it accordingly. Since there aren't such validations in place, and no restrictions imposed on the request content types, the above truly is an error at server side and hence, the 500 response code returned to the client is correct. 

Suppose we modify the above sample as follows:
```ballerina
import ballerina.net.http;
@http:configuration {
    basePath:"/test"
}
service<http> service1 {
    @http:resourceConfig {
        consumes:["json"]
    }
    resource echo1 (http:Request req,http:Response res) {
        var var1 = req.getJsonPayload();
        res.setJsonPayload(var1);
        res.send();
    }
}
```
Now, we are explicitly stating that this resource only accepts JSON payloads. Attempts to send invalid JSON strings as the payload as follows results in a 400 response code to the user (which is the correct response code).
`curl -v -d "TEST" -HContent-Type:application/json http://localhost:9090/test/echo1`

**Comment by shafreenAnfar** [comment] 2017-11-13 06:30
As per the above comment, I am closing this issue.

**Closed by shafreenAnfar** 2017-11-13 06:30 UTC
Labels: bug, Type/Bug
