### ISSUE TITLE
[Documentation] Error in the Constrained JSON sample

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3426] opened 2017-10-03 13:07 UTC
Errors shown when the Constrained JSON sample is copied from the ballerina by example site.

Reason is due to having multiple line doc descriptions as follows.

```
@doc:Description {
        value: "Resource to get employee for the person by index which" +
        " can be invoked with /people/employee?index={index}"
    }
```

**Comment by samgnaniah** [comment] 2017-11-02 15:32
Assign to me.

**Comment by samgnaniah** [comment] 2017-11-06 12:18
Cannot reproduce this. Please check: https://github.com/ballerinalang/ballerina/tree/master/samples/ballerina-by-example/examples/constrained-json

**Comment by anupama-pathirage** [comment] 2017-11-07 09:28
This issue is fixed with 0.94.0 release

https://ballerinalang.org/docs/by-example/constrained-json

**Closed by anupama-pathirage** 2017-11-07 09:28 UTC
Labels: Docs
