### ISSUE TITLE
Unable to define multiple xpaths for dynamic payloads

### ISSUE THREAD

**Issue by sashikamw** [ballerinalang/ballerina#2543] opened 2017-06-09 09:31 UTC
**Environment** 
Ballerina 0.87 release

**Issue**
The requirement is to extract a value from dynamic payloads using the XPath expression. 

Sample Service:
```
@http:POST{}
    resource XPathResourcetest(message m) {
        string empID = "990";
        xml incomingPayload = messages:getXmlPayload(m);
        // filter messages based on stock name
        string EmpPerID = xmls:getString(incomingPayload, "//EmployeePersonalDetails/ID/text()");
        string EmpComID = xmls:getString(incomingPayload, "//EmployeeDepartmentInfo/ID/text()");
        
        system:println("++++++++++++++++++++#" + EmpPerID +EmpComID);
        message response = {};

        if (empID == EmpPerID) {
            string emppayload = "Hello Peter";
            messages:setStringPayload(response, emppayload);
            
        } else {
            
            string errorpayload = "Message do not meet the filter criteria";
            messages:setStringPayload(response, errorpayload);
            
        }

        reply response;
    }

```
Sample Payloads
```
<EmployeePersonalDetails>
<ID>990</ID>
<Name>Peter</Name>
<Age>27</Age>
<City>Colombo</City>
</EmployeePersonalDetails>

<EmployeeDepartmentInfo>
<ID>990</ID>
<Team>EI</Team>
<SubTeam>EE</SubTeam>
</EmployeeDepartmentInfo>
```
Error message
`error in ballerina program: failed to get string from xml. Error while executing xpath: Failed to get string from xml. The xpath '//EmployeeDepartmentInfo/ID/text()' does not match any element.`

As a workaround used try-catch blocks to achieve the requirement

**Comment by SupunS** [comment] 2017-08-11 20:05
The problem is that the xpaths are throwing errors, if not find a match. This issue is tracked with #3103. Hence closing this issue.

**Closed by SupunS** 2017-08-11 20:05 UTC
