### ISSUE TITLE
Cannot access constants, global variables in the same package but different files

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#2902] opened 2017-07-13 06:33 UTC
```
|-org
| |- wso2
|    |- utils
|       |- const.bal
|       |- utils.bal
|- main.bal
```

**const.bal -** 
```
package org.wso2.utils;

const string HELLO = "Hello";
```

**utils.bal -**
```
package org.wso2.utils;

function generateGreeting (string name) (string) {
    return HELLO + " " + name + " !!!";
}
```

**main.bal -**
```
import org.wso2.utils;
import ballerina.lang.system;

function main (string[] args) {
    string greeting = utils:generateGreeting(args[0]);
    system:println(greeting);
}
```

When we run the above program(using Ballerina 0.90), we get the following error.
```
org/wso2/utils/utils.bal:4: undefined symbol 'org.wso2.utils:HELLO'
```

**Comment by erandidesilva** [comment] 2017-07-13 09:53
Similar issue https://github.com/ballerinalang/ballerina/issues/2429

**Comment by djkevincr** [comment] 2017-07-18 05:01
This is fixed by PR https://github.com/ballerinalang/ballerina/pull/2401

**Comment by lankavitharana** [comment] 2017-11-15 07:41
Cannot reproduce in the latest source, tested in 0.95.0 and master

**Closed by lankavitharana** 2017-11-15 07:41 UTC
Labels: Type/Bug
