### ISSUE TITLE
Commenting out import statements stops running

### ISSUE THREAD

**Issue by igunawardana** [ballerinalang/ballerina#3039] opened 2017-07-22 11:35 UTC
When an `import` statement is commented, it stops the program running.

$ ballerina run oxygeon/core/
oxygeon/core/NewsAgent.bal:6: unused import package '"ballerina.lang.jsons"'
$

**Comment by SupunS** [comment] 2017-08-11 18:46
Duplicate of #2286

**Closed by SupunS** 2017-08-11 18:46 UTC
