### ISSUE TITLE
ClientConnector doesn't work for some links

### ISSUE THREAD

**Issue by deQuota** [ballerinalang/ballerina#2393] opened 2017-05-21 18:23 UTC
Here is my program for gain data from https://opensky-network.org/api/states/all (this link returns a json) . But when I run it, shows a timeout error after 180s.  However other links which are returning jsons are working fine with this program.
`import ballerina.lang.jsons;
import ballerina.lang.messages;
import ballerina.lang.system;
import ballerina.net.http;

connector OpenAir(){

		http:ClientConnector addrssJson = create http:ClientConnector("https://opensky-network.org/api/states/all");
		
		action getData(OpenAir oa)(message){
		message request = {};
		message response = http:ClientConnector.post(addrssJson,"",request);
		return response;
		}
		
		
		
		
		
}
function main(string[] args){
		
		OpenAir oa = create OpenAir();
		message response = OpenAir.getData(oa);
		json resonseInJson = messages:getJsonPayload(response);
		system:println(jsons:toString(resonseInJson));
		}`

**Comment by gludington** [comment] 2017-05-23 16:02
Perhaps this is an issue with https and the ClientConnector?  I note that I cannot hit

http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1
https://api.chucknorris.io/jokes/random

or any other https api I try, though it seems to work for standard http

**Comment by deQuota** [comment] 2017-05-23 18:42
Try with this one,
https://graph.facebook.com/cnn
It retrieves follwing json fine with above program even though it is https.
{
   "error": {
      "message": "An access token is required to request this resource.",
      "type": "OAuthException",
      "code": 104,
      "fbtrace_id": "Er83k2CHybd"
   }
}

**Comment by gludington** [comment] 2017-05-23 21:26
Confirmed - I get the same response you specify.  I have found other http only ones that fail, such as:

http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1

The follow up question would be, where can we access logging or debugging at the lower levels where these are failing to help troubleshoot this?

**Comment by gludington** [comment] 2017-05-23 22:42
After building and running from git, I get the same timeout behavior with https://graph.facebook.com/cnn.  In the console, I see:
```
error in ballerina program: failed to invoke 'get' action in ClientConnector. Error when creating channel for route graph.facebook.com-443
	 at ballerina.net.http:get(chuck2.bal:11)
	 at random(chuck2.bal:8)
	 at .:chuck(chuck2.bal:5)

Exception in thread "BLangWorker-3" org.ballerinalang.util.exceptions.BallerinaException: Cannot handle error using the error handler for: https
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:136)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:100)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by deQuota** [comment] 2017-05-26 20:44
@gludington  I have tried the following one for your weather API which didn't worked previously

`import ballerina.lang.jsons;
import ballerina.lang.messages;
import ballerina.net.http;
import ballerina.net.uri;

@http:BasePath{value: "/weather"}

service chuck {
    string address = "http://samples.openweathermap.org";
    http:ClientConnector chuckService = create http:ClientConnector(address);
	
    @http:GET{}
    @http:Path{value:"/test"}
    resource productsInfo(message m) {
	    string city = "London";
		string appID = "b1b15e88fa797225412429c1c50c122a1";
        message response = http:ClientConnector.get(chuckService,"/data/2.5/weather?q="+uri:encode(city)+"&"+"appid="+uri:encode(appID), m);
		
		json resonseInJson = messages:getJsonPayload(response);
		jsons:toString(resonseInJson);
        reply response;
    }
	
        
}`

However now this returns json results, but not continuously. When we refresh the browser time to time it shows an error.

**Comment by gludington** [comment] 2017-06-07 18:54
@deQuota Yes, I have had similar results with some other URLs, where the request goes out through the ClientConnector, but never returns, and as such the user's client appears to time out.

**Comment by shafreenAnfar** [comment] 2017-08-23 10:46
Hi All,

This is due to not sending the SNI details along with SSL handshake. This has been fixed in 0.93 release.

**Comment by deQuota** [comment] 2017-08-23 12:03
Great!
I couldn't use some APIs in the ballerina hackathon because of this issue, however it is good to hear that the issue has been solved.

**Comment by shafreenAnfar** [comment] 2017-11-28 07:51
As the issue is resolved, I am closing this issue. Thank you for reporting.

**Closed by shafreenAnfar** 2017-11-28 07:51 UTC
Labels: Type/Bug
