### ISSUE TITLE
Getting java exception at service invocation with Non-blocking mode

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1887] opened 2017-02-16 10:18 UTC
Checking on 795811b  with non-blocking mode
Steps:
1. Deploy the code attached here
[workerservice.txt](https://github.com/ballerinalang/ballerina/files/779734/workerservice.txt)

2. Invoke the service 

Issue:
Getting java exception on the ballerina console. See [2] . Same scenario working on blocking mode

Error [2]:
asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina service /home/asankav/svn/ballerina_test/services/artifacts/wokerSupport/workerservice.bal 
Started listener http-9090
ballerina: deployed service(s) in workerservice.bal
I am 1

I am 2
Hello in wadakaru1
I am 3
Hello in wadakaru2
error in ballerina program: 

Exception in thread "pool-2-thread-2" org.wso2.ballerina.core.exception.BallerinaException: Cannot handle error using the error handler for : null
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleErrorFromOutbound(ServerConnectorMessageHandler.java:159)
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleOutbound(ServerConnectorMessageHandler.java:117)
	at org.wso2.ballerina.core.runtime.threadpool.ResponseWorkerThread.run(ResponseWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: org.wso2.ballerina.core.exception.BallerinaException: org.wso2.ballerina.core.exception.BallerinaException: error in ballerina program: 
	at org.wso2.ballerina.core.runtime.errors.handler.DefaultServerConnectorErrorHandler.handleError(DefaultServerConnectorErrorHandler.java:45)
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleErrorFromOutbound(ServerConnectorMessageHandler.java:156)
	... 5 more
Caused by: org.wso2.ballerina.core.exception.BallerinaException: error in ballerina program: 
	... 6 more
Exception in thread "pool-2-thread-4" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
	at java.util.Vector.get(Vector.java:759)
	at org.wso2.ballerina.core.runtime.errors.handler.ErrorHandlerUtils.getStackTrace(ErrorHandlerUtils.java:110)
	at org.wso2.ballerina.core.runtime.errors.handler.ErrorHandlerUtils.getServiceStackTrace(ErrorHandlerUtils.java:70)
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleErrorFromOutbound(ServerConnectorMessageHandler.java:145)
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleOutbound(ServerConnectorMessageHandler.java:117)
	at org.wso2.ballerina.core.runtime.threadpool.ResponseWorkerThread.run(ResponseWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

**Comment by lankavitharana** [comment] 2017-03-24 17:13
cannot reproduce, Get the same exception [1] for both blocking and non blocking in latest snapshot build. Used file 
[echo.txt](https://github.com/ballerinalang/ballerina/files/868658/echo.txt) because of the new syntax changes.


[1] - exception in workerwadakaru1 : error in ballerina program: failed to invoke 'post' action in ClientConnector. Connection timeout, www.mocky.io-80
	 at ballerina.net.http:post(echo.bal:22)

**Comment by chanakaudaya** [comment] 2017-06-30 12:40
Closing as per the above comment.

**Closed by chanakaudaya** 2017-06-30 12:40 UTC
