### ISSUE TITLE
Ballerina 0.85 No error shown in logs 

### ISSUE THREAD

**Issue by tharindu1st** [ballerinalang/ballerina#2272] opened 2017-04-04 10:42 UTC
Hi,

import ballerina.lang.jsons;
import ballerina.net.http;
@http:BasePath {
value:"/api"
}
service Service1 {

@http:GET {
}
resource api_all(message m) {
http:ClientConnector productionEndpoint = create http:ClientConnector();
http:ClientConnector sandboxEndpoint = create http:ClientConnector(getUrlFromKey("endpoint_api1_1.0.0"));
message response;
string endpointType;
string productionType;
endpointType = "production";
productionType = "production";
if (endpointType == productionType) {
response = http:ClientConnector.execute(productionEndpoint, "post", "", m);

}
else {
response = http:ClientConnector.execute(sandboxEndpoint, "post", "", m);

}
reply response;	
}
}
function getUrlFromKey(string key)(string ) {
map endpointMap = {};
endpointMap["endpoint_api1_1.0.0"] = "http://www.mocky.io/v2/58e1ea9d250000ca1463311c";
endpointMap["endpoint_api2_1.0.0"] = "http://localhost";
endpointMap["endpoint_api3_1.0.0"] = "http://www.mocky.io/v2/58e20a7c250000b916633192";
endpointMap["endpoint_api5_1.0.0"] = "http://www.mocky.io/v2/58e20a7c250000b916633192";
endpointMap["endpoint_api6_1.0.0"] = "http://www.mocky.io/v2/58e20a7c250000b916633192";
string endpoint = endpointMap[key];
return endpoint;

}
function getEndpointFromKey(string key)(string ) {
string jsonEndpoint = getUrlFromKey(key);
json endpoint = (json )jsonEndpoint;
string url = jsons:getString(endpoint, "$.url");
return url;

}

Created the above ballerina file once run as a service exit with
**ballerina:0**

**Comment by pubudu91** [comment] 2017-08-11 19:07
Can you please elaborate on the issue you faced here?

**Comment by anupama-pathirage** [comment] 2017-11-09 04:33
Tested below code with 0.95.0 release

```ballerina
import ballerina.net.http;

@http:configuration {basePath:"/api"}
service<http> Service1 {

        resource api_all(http:Request req, http:Response res) {
                endpoint<http:HttpClient> productionEndpoint {
            create http:HttpClient(getUrlFromKey("endpoint_api2_1.0.0"), {});
        }
                endpoint<http:HttpClient> sandboxEndpoint {
            create http:HttpClient(getUrlFromKey("endpoint_api1_1.0.0"), {});
        }

                string endpointType;
                string productionType;
                endpointType = "production";
                productionType = "production";
                http:Response response = {};
                if (endpointType == productionType) {
                        response,_ = productionEndpoint.execute("post", "", req);
                }
                else {
                        response,_ = sandboxEndpoint.execute("post", "", req);
                }
                res.forward(response);
        }
}

function getUrlFromKey(string key)(string ) {
        map endpointMap = {};
        endpointMap["endpoint_api1_1.0.0"] = "http://www.mocky.io/v2/58e1ea9d250000ca1463311c";
        endpointMap["endpoint_api2_1.0.0"] = "http://localhost";
        endpointMap["endpoint_api3_1.0.0"] = "http://www.mocky.io/v2/58e20a7c250000b916633192";
        endpointMap["endpoint_api5_1.0.0"] = "http://www.mocky.io/v2/58e20a7c250000b916633192";
        endpointMap["endpoint_api6_1.0.0"] = "http://www.mocky.io/v2/58e20a7c250000b916633192";
        var endpoint1, _  = (string) endpointMap[key];
        return endpoint1;
}

function getEndpointFromKey(string key)(string ) {
        string jsonEndpoint = getUrlFromKey(key);
        json endpoint1 = (json )jsonEndpoint;
        json url = endpoint1["url"];
        return url.toString();
}
```
Issue couldn't reproduced and sample code worked fine, hence resolving this issue.

**Closed by anupama-pathirage** 2017-11-09 04:33 UTC
Labels: Type/Bug
