### ISSUE TITLE
[Debugger] Errors when debugging a program with fork-join 

### ISSUE THREAD

**Issue by pahans** [ballerinalang/ballerina#4134] opened 2017-11-23 08:44 UTC
The attached ballerina program which uses a fork-join runs successfully. But when you try to debug, getting the following errors. (add a debug point to line number 4)

```ballerina
function main (string[] args) {
    fork {
       worker addWorker1 {
            int i1 = 5;
        }
        worker subWorker2 {
            int i1 = 5;
        }
    } join (all) (map airlineResponses) {

    }
timeout(60)(map m){

}}
```

**Comment by lankavitharana** [comment] 2017-11-27 13:19
duplicate of https://github.com/ballerinalang/ballerina/issues/3274

**Closed by lankavitharana** 2017-11-27 13:19 UTC
Labels: Type/Bug
