### ISSUE TITLE
NPE when concatenating constant and string

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#2262] opened 2017-03-31 09:45 UTC
Consider the following project structure.
```
project
  |-org
      |-test
          |-const.bal
          |-main.bal
```
const.bal-
```
package org.test;

const string HELLO = "Hello ";
```

main.bal
```
package org.test;

import ballerina.lang.system;

function main (string[] args) {
    system:println(HELLO + args[0]);
}
```

When we run `/home/shan/Desktop/ballerina-0.85/bin/ballerina run main org/test Shan`, we get `ballerina: unexpected error occurred` message.

If the constant is defined in the same file, we don't get this error.

Log -
```
[2017-03-31 14:53:13,347]  SEVERE {org.ballerinalang.launcher.Main main} - ballerina: unexpected error occurred 
java.lang.NullPointerException
	at org.ballerinalang.util.semantics.SemanticAnalyzer.verifyBinaryExprType(SemanticAnalyzer.java:2074)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.verifyBinaryArithmeticExprType(SemanticAnalyzer.java:2047)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:1464)
	at org.ballerinalang.model.expressions.AddExpression.accept(AddExpression.java:60)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visitSingleValueExpr(SemanticAnalyzer.java:2036)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visitBinaryExpr(SemanticAnalyzer.java:2031)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.verifyBinaryExprType(SemanticAnalyzer.java:2059)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.verifyBinaryArithmeticExprType(SemanticAnalyzer.java:2047)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:1464)
	at org.ballerinalang.model.expressions.AddExpression.accept(AddExpression.java:60)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visitSingleValueExpr(SemanticAnalyzer.java:2036)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:1346)
	at org.ballerinalang.model.expressions.FunctionInvocationExpr.accept(FunctionInvocationExpr.java:101)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:1089)
	at org.ballerinalang.model.statements.FunctionInvocationStmt.accept(FunctionInvocationStmt.java:46)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:991)
	at org.ballerinalang.model.statements.BlockStmt.accept(BlockStmt.java:59)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:394)
	at org.ballerinalang.model.BallerinaFunction.accept(BallerinaFunction.java:190)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:227)
	at org.ballerinalang.model.BLangPackage.accept(BLangPackage.java:254)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:178)
	at org.ballerinalang.model.BLangProgram.accept(BLangProgram.java:167)
	at org.ballerinalang.BLangProgramLoader.loadMain(BLangProgramLoader.java:70)
	at org.ballerinalang.launcher.BProgramRunner.runMain(BProgramRunner.java:44)
	at org.ballerinalang.launcher.Main$RunMainCmd.execute(Main.java:287)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:218)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:52)
 ```

**Comment by lankavitharana** [comment] 2017-05-04 12:28
Pull [1] will fix the first issue, second issue is already fixed in current source 

[1] - https://github.com/ballerinalang/ballerina/pull/2321

**Comment by SupunS** [comment] 2017-05-15 04:57
Fixed in v 0.87

**Comment by SupunS** [comment] 2017-05-17 09:57
Seems this is not fixed, hence reopening the issue.

**Comment by lankavitharana** [comment] 2017-05-30 09:58
this will be fixed with pull https://github.com/ballerinalang/ballerina/pull/2401

**Comment by lankavitharana** [comment] 2017-11-15 07:41
cannot reproduce in latest source, tested in 0.95.0 and master

**Closed by lankavitharana** 2017-11-15 07:41 UTC
Labels: Type/Bug
