### ISSUE TITLE
No proper error message when an ArrayIndexOutOfBoundsException is thrown in Java code

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/ballerina#3333] opened 2017-09-19 08:49 UTC
When an `ArrayIndexOutOfBoundsException` is thrown in native code and is escalated right up to the catch clause in the `main()` method of `Main.java`, the error message shown for it is not useful/informative. Given below is an example for such an error message: 
`ballerina: 1`

The reason for the above message is because the message of `ArrayIndexOutOfBoundsException` only contains the index which caused the exception to be thrown.

**Comment by SupunS** [comment] 2017-11-21 07:49
Ideally, ArrayIndexOutOfBoundsException shouldn't be thrown from the native code. It has to be handled properly.

@pubudu91, can you provide specific scenario/sample code to reproduce this?

**Comment by pubudu91** [comment] 2017-11-21 18:08
@SupunS True, that indicates an error in Ballerina developer's part. Came across this when working on a feature. Opened this issue to keep track of cases where simply using the error message of the exception thrown in Java code doesn't work. In this particular case, the correct error given to the user should've been `ballerina: internal error occurred`. But IIRC, currently only NPEs in Java code result in the aforementioned error message.

**Comment by SupunS** [comment] 2017-11-22 12:15
Great! I'm closing this issue then, since we don't have a specific scenario to reproduce. 
Please do reopen, or create a new issue, if you encounter a similar issue for a specific scenario.

**Closed by SupunS** 2017-11-22 12:15 UTC
Labels: Type/Bug
