### ISSUE TITLE
If a resource do not have a reply statement when you run the service you would get "ballerina: -1"

### ISSUE THREAD

**Issue by hevayo** [ballerinalang/ballerina#2654] opened 2017-06-22 11:55 UTC
Checked on 0.88 release. Please try to run the following service. 

`package wso2.hospital.sample;`
`import ballerina.net.http;`

`service Service1 {`
`    @http:GET {}`
`    @http:Path { value: "/dest" }`
`    resource Resource1 (message m) {`
`    }`
`}`

It will give you "ballerina: -1" as the command output. Instead of -1 it will be helpful to get a meaningful error message.

**Comment by chanakaudaya** [comment] 2017-08-11 19:05
cannot reproduced in the latest 0.92-SNAPSHOT version. Hence closing the issue.

**Closed by chanakaudaya** 2017-08-11 19:05 UTC
