### ISSUE TITLE
When multiple files are under same package global variable in one file is not visible in a client connector in a different file

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerinalang/ballerina#3033] opened 2017-07-22 10:54 UTC
When multiple files are under same package, when defining a global variable in one file, and used in a client connector in a different file, we are getting "undefined symbol" error. 

For example, define following in one file. 
string GITHUB_API_URI = "https://api.github.com";

Then create another file with same package, create a client connector. 
http:ClientConnector githubEP = create http:ClientConnector(GITHUB_API_URI);

This global variable is visible for functions etc. in some other file.

**Comment by erandidesilva** [comment] 2017-07-22 12:04
Related issue https://github.com/ballerinalang/ballerina/issues/2902

**Comment by lankavitharana** [comment] 2017-07-22 12:20
This should be fixed by pull https://github.com/ballerinalang/ballerina/pull/2401

**Comment by yasassri** [comment] 2017-09-19 04:23
This seems to be causing issues in the automation framework, Can we get this PR merged?

**Comment by lankavitharana** [comment] 2017-11-15 07:58
Cannot reproduce this in latest source, tested in 0.95.0 pack and current master. 
Issue was when we define symbols, if the symbols refer other symbols in a different file (same package) by the time we define the current symbol, the reference symbol may not be defined, so trying to resolve that will cause failure, this happens because we do the symbol resolving and definition in single pass, but with new semantic rewrite, this should be fixed, because with new implementation we are doing the symbol definition and resolving in multiple passes.

**Closed by lankavitharana** 2017-11-15 07:58 UTC
Labels: bug, Type/Bug
