### ISSUE TITLE
[JMS] A map payload cannot be sent as an object message

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2603] opened 2017-06-14 12:55 UTC
```
    map dataMap = {"country":"US", "currency":"Dollar", "states":"50"};
    map mapMessage = {"MapData":dataMap};
    messages:setMapPayload(queueMessage, mapMessage);

    jms:ClientConnector.send(jmsEP, "MyQueue", "ObjectMessage", queueMessage);
    system:println(queueMessage);
```

//prints null

**Comment by SupunS** [comment] 2017-10-18 05:53
Duplicate of https://github.com/ballerinalang/connector-jms/issues/9

**Closed by SupunS** 2017-10-18 05:53 UTC
