### ISSUE TITLE
Can not access service level variable concurrently inside resource

### ISSUE THREAD

**Issue by nuwanw** [ballerinalang/ballerina#1923] opened 2017-02-17 01:27 UTC
When accessing the below resource concurrently, response value get corrupted. 

import ballerina.lang.message;

@http:BasePath("/productsservice")
service productmgt {

    xml payload = `<product>name</product>`;

    @http:GET
    resource product (message m) {

    message response = {};
    message:setXmlPayload(response, payload);

    reply response;
    }

}

**Comment by kasunbg** [comment] 2017-02-24 02:37
Fix - https://github.com/ballerinalang/ballerina/pull/2101

**Comment by SupunS** [comment] 2017-03-03 11:56
Relates to https://github.com/ballerinalang/ballerina/issues/1629

**Comment by SupunS** [comment] 2017-11-22 11:55
Currently, by design, ballerina service level and connector level variables are not thread safe. Only map type is thread safe by default.
This is future improvement, and will be tracked via #1629. Hence closing this issue.

**Closed by SupunS** 2017-11-22 11:55 UTC
Labels: bug, Type/Bug
