### ISSUE TITLE
Same Request object can not reuse

### ISSUE THREAD

**Issue by IshikaGodage** [ballerinalang/ballerina#3966] opened 2017-11-08 09:44 UTC
1.
```
import ballerina.net.http;

function main (string[] args){
	endpoint<http:HttpClient> gitEnd {
	create http:HttpClient("https://api.github.com",{});	
	}


	http:Request req = {};
	http:Response resp = {};
	json jsonRes;

	int i = 0;
	
	while (i < 2){
		resp, _ = gitEnd.get("/orgs/wso2/repos", req);
		jsonRes = resp.getJsonPayload();
		print("Iteration : " + <string>i + " ");
		println("jsonRes output: " + jsonRes.toString());
		i = i + 1;
	}
}
----------------------------------------------------------------------------------------------------------------------------------
Iteration : 0 jsonRes output: [{"id":1333653,"name":"wsf","full_name":"wso2/wsf","owner":{"login":"wso2","id":533043
```

2.
```
import ballerina.net.http;

function main (string[] args){

	endpoint<http:HttpClient> gitEnd {
	create http:HttpClient("https://api.github.com",{});
	}

	http:Response resp = {};
	json jsonRes;

	int i = 0;
	while (i < 2){
		http:Request req = {};

		resp, _ = gitEnd.get("/orgs/wso2/repos", req);
		jsonRes = resp.getJsonPayload();
		print("Iteration : " + <string>i + " ");
		println("jsonRes output: " + jsonRes.toString());
		i = i + 1;
	}
}
----------------------------------------------------------------------------------------------------------------------------------
Iteration : 0 jsonRes output: [{"id":1333653,"name":"wsf","full_name":"wso2/wsf","owner":{"login":"wso2","id":533043,"avatar_url"
Iteration : 1 jsonRes output: [{"id":1333653,"name":"wsf","full_name":"wso2/wsf","owner":{"login":"wso2","id":533043,"avatar_url":
```

**Comment by arunans23** [comment] 2017-11-08 09:56
Same issue came for me too when sending two http requests sequentially. 

```
import ballerina.net.http;

function main (string[] args){

    endpoint<http:HttpClient> gitEnd {
        create http:HttpClient("https://api.github.com",{});
    }

    http:Response resp = {};
    http:Response resp1 = {};

    http:Request req = {};

    resp, _ = gitEnd.get("/orgs/wso2/repos", req);
    resp1, _ = gitEnd.get("/orgs/wso2/repos", req);

    json jsonRes = resp.getJsonPayload();
    json jsonRes1 = resp1.getJsonPayload();

    println("jsonRes1 output: " + jsonRes.toString());
    println("jsonRes1 output: " + jsonRes1.toString());
}
```

When executed there is nothing printed on the terminal. The program seems to be hanged.

**Comment by SupunS** [comment] 2017-11-22 12:40
This is a duplicate of https://github.com/ballerinalang/ballerina/issues/1418. Hence closing the issue. 

However, to add some context, this is the intended behaviour since the incoming message contains a stream, and once it is consumed, it can no longer be used again. But we are discussing to alter this behaviour. Progress can be tracked via #1418.

**Closed by SupunS** 2017-11-22 12:40 UTC
Labels: Type/Bug
