### ISSUE TITLE
json order = (messages:getJsonPayload(m)).order syntax is not supported

### ISSUE THREAD

**Issue by R-Rajkumar** [ballerinalang/ballerina#2812] opened 2017-07-02 02:29 UTC
The following syntax is not supported. Have to create an intermediate variable and then access the fields as a workaround. 

json order = (messages:getJsonPayload(m)).order;

**Comment by SupunS** [comment] 2017-08-11 17:29
Duplicate of #2674

**Closed by SupunS** 2017-08-11 17:29 UTC
Labels: bug
