### ISSUE TITLE
[Improvement] Cannot declare anything above endpoints

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#4095] opened 2017-11-20 06:44 UTC
In functions, the endpoint should always be the very first statement, otherwise it will give an error. If I want to declare the url as a separate variable as follows I cannot do so (gives an error. I have to use a global variable to achieve this.) This is an unnecessary restriction imposed on the user

```
function getAccessToken()(string access_token){
    string url = "https://www.googleapis.com/oauth2/v4/token";
    endpoint<http:HttpClient> gmailTokenEP {
        create http:HttpClient(url, {});
    }
```

**Comment by anupama-pathirage** [comment] 2017-11-20 11:12
Same issue https://github.com/ballerinalang/ballerina/issues/3962

**Comment by SupunS** [comment] 2017-11-27 06:26
This is by design. Therefore closing the issue

**Closed by SupunS** 2017-11-27 06:26 UTC
Labels: duplicate, Type/Improvement
