### ISSUE TITLE
Incorrect error when same variable name is duplicated

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3540] opened 2017-10-10 10:09 UTC
Affected Version: 0.93

![screenshot from 2017-10-10 15-34-21](https://user-images.githubusercontent.com/7681361/31381095-2281e040-add1-11e7-8c18-a18d1ac9769d.png)

**Comment by SupunS** [comment] 2017-10-17 09:47
I couldn't reproduce this in v0.93.1-SNAPSHOT and v0.92. Whats the version u tried?
Can you attach the source?

**Comment by SupunS** [comment] 2017-10-19 06:08
Closing the issue since its nor reproducible in the latest version. Please do reopen if you encounter the issue again.

**Closed by SupunS** 2017-10-19 06:08 UTC
