### ISSUE TITLE
Error in validating multiple left hand expression of assignment statement

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#2639] opened 2017-06-20 15:01 UTC
Consider the following sample : 
```
import ballerina.lang.system;

struct Employee {
    string name;
    int age;
    string address;
}

struct Person {
    string first_name;
    string last_name;
    int age;
    string city;
}

function main (string[] args) {
    Employee e = {name: "John",age: 30,address: "London"};
    Person p = {};
    
    string x;
    string y;

    transform {
        x, y = getMyStrings(e.name);
        //p.first_name, p.last_name = getMyStrings(e.name);
        p.age = e.age;
        p.city = e.name;
    }
    system:println(x + "," +  y);
}

function getMyStrings(string str) (string, string){
    return str + "1",str + "2";
}

```
`x, y = getMyStrings(e.name);` is a valid statement and `p.first_name, p.last_name = getMyStrings(e.name);` throws the error - "`test4.bal:25: 'p' is repeated on the left side of assignment`"

The left expression check does not validate from struct field level.

**Comment by maheeka** [comment] 2017-06-23 13:06
@djkevincr, as per my understanding, with the introduction of var with assignment statement; the same variable validation only needs to be included with var scenario and must be removed for other cases. Can we add this since returning multiple is a basic scenario for transform statement?

**Comment by sameera-jayasoma** [comment] 2017-06-25 05:52
This will be fixed with the following PR.

https://github.com/ballerinalang/ballerina/pull/2695

**Comment by SupunS** [comment] 2017-08-11 17:27
Tested in v0.91.1-SNAPSHOT. Couldn't reproduce. Hence closing the issue.

**Closed by SupunS** 2017-08-11 17:27 UTC
