### ISSUE TITLE
Cannot cast to int when retrieving params from a queryParam map

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#4029] opened 2017-11-15 09:05 UTC
Cannot cast to int type when retrieving qyery params from a queryParam map

1. I have a service which I invoke as below
`http://localhost:9090/account/newaccount?accountType=2&currency=1`
2. The code segment which retrieves these params are as follows
```
map params = req.getQueryParams();
var accountType, err22 = (int)params.accountType;
```

**Issue**
1. When I invoke this service, I get an error as below
`{msg:"'string' cannot be cast to 'int'", cause:null, stackTrace:[{caller:"ABCOnlineBankingAccountService.createNewAccount", packageName:"services", fileName:"Main.bal", lineNumber:116}], sourceType:"string", targetType:"int"}`

2. When I use conversion instead of casting I get a compilation error.
`var accountType, err22 = <int>params.accountType;`
`error: services/Main.bal:116:34: incompatible types: 'any' cannot be convert to 'int', use cast expression`

**Workaround**
As a workaround, I have done it like below which is an unnecessary burden for the user
```
        map params = req.getQueryParams();
        var accType, _ = (string)params.accountType;
        var accountType, _ = <int>accType;
```

**Comment by lankavitharana** [comment] 2017-11-16 08:04
This is by design, we receive query params and path params as strings, earlier we did the conversion and provided with correct type, but we have changed the design so that user has to do the conversion if needed.
So in current map implementation, value is always an "any" so you have to cast the the value to correct type and then do the conversion. (there are plans for having maps with specific types as values)

**Comment by shafreenAnfar** [comment] 2017-11-22 08:17
As per the comment, I am closing this issue.

**Closed by shafreenAnfar** 2017-11-22 08:17 UTC
Labels: Type/Bug
