### ISSUE TITLE
[Datatables] When the target struct is having lesser parameters than source, the data is not fetched successfully

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2601] opened 2017-06-14 10:09 UTC
**Target struct**
```
struct EmpMissingParams{
    int emp_no;
    string birth_date;
    string first_name;
    string last_name;
    string gender;
}
```
**Sample source**

```
function getAlEmployeesMissingParamsInStruct () (int, errors:TypeCastError){
    int i=0;
    errors:Error ex;
    sql:Parameter[] parameters = [];
    datatable df;
    errors:TypeCastError err;
    sql:ClientConnector connectorInstance = connectorInit:init();
    df = sql:ClientConnector.select (connectorInstance, "select * from employees", parameters);
    while (datatables:hasNext(df)) {
        any para = datatables:next(df);
        EmpMissingParams empM;
        empM, err = (EmpMissingParams)para;
        if (err == null) {
            system:println(empM.emp_no);
            system:println(empM.birth_date);
            system:println(empM.first_name);
            system:println(empM.last_name);
            system:println(empM.gender);
            i = i+1;
        }
        else{
            errors:getStackTrace((errors:Error)err);
            err = {msg:"Error in retrieving data: Less parameters than fetched"};
        }

    }
    return i, err;
}
```

According to struct equilance rules when the target struct is lesser than the source, the cast should happen successfully.

**Comment by anupama-pathirage** [comment] 2017-06-15 17:56
Duplicate of #2598

Tested a scenario where the target struct is having lesser parameters than returned struct from the next method and it works without any issue. The given sample is giving error due to #2598

**Closed by anupama-pathirage** 2017-06-15 17:56 UTC
Labels: bug
