### ISSUE TITLE
Improve the error message

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/ballerina#1995] opened 2017-02-19 09:12 UTC
Error shown for the bal file[1] is not descriptive, and it doesn't tell me which line has error code.

Error: 
ballerina: org.ballerinalang.model.types.BXMLType cannot be cast to org.ballerinalang.model.VariableDef 

[1] attached testXml.txt
[testXml.txt](https://github.com/ballerinalang/ballerina/files/785678/testXml.txt)

**Comment by nuwanw** [comment] 2017-02-22 07:11
tried with given sample testXml.txt file by replacing xmlutils with xmls because of package refactoring. could not reproduce above mentioned error.

**Comment by SupunS** [comment] 2017-02-27 04:19
This is fixed with PR: https://github.com/ballerinalang/ballerina/pull/2013

**Closed by SupunS** 2017-02-27 04:19 UTC
