### ISSUE TITLE
String.contains() function doesn't support for regex.

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerinalang/ballerina#4062] opened 2017-11-17 08:54 UTC
I need to read data from database table and filter those data using regular expression. Since Ballerina `String.contains()` function doesn't support for regular expressions, I couldn't do it in Ballerina side. If you can change the implementation of `String.contains()` or add a new function to match strings with regular expressions, It would help to develop these kind of scenarios.

**Comment by anupama-pathirage** [comment] 2017-11-17 09:08
Duplicate of https://github.com/ballerinalang/ballerina/issues/2507 and https://github.com/ballerinalang/ballerina/issues/2798

**Comment by SupunS** [comment] 2017-11-27 05:37
Closing since this is a duplicate

**Closed by SupunS** 2017-11-27 05:37 UTC
Labels: duplicate, Type/New Feature
