### ISSUE TITLE
Both the value and the error are populated in type conversion

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#4032] opened 2017-11-15 12:29 UTC
In the below code segment, when the  ` result, er = <json>dt;` is executed both the result and the error get populated. The result will be successfully received by the client, but an error will also be logged

```
public function getPendingApprovalAccountList () (json result, error err) {
    endpoint<sql:ClientConnector> ep {
        init();
    }

    TypeConversionError er;
    sql:Parameter[] parameters = [];
    int accStatus = cons:ACC_STATUS_APPROVAL_PENDING;
    string query = "select * from Account where account_status=?";

    try {
        sql:Parameter para1 = {sqlType:"integer", value:accStatus, direction:0};
        parameters = [para1];
        datatable dt = ep.select(query, parameters);
        result, er = <json>dt;
        println(result);

        if (er != null) {
            log:printError("getPendingApprovalAccountList: Error occurred in conversion");
        }

    }
    catch (error e) {
        err = e;
    }
    return;
}
```

**Comment by anupama-pathirage** [comment] 2017-11-15 17:49
Related issue https://github.com/ballerinalang/ballerina/issues/2887

**Comment by SupunS** [comment] 2017-11-17 08:30
Closing this issue, since its a duplicate of #2887

**Closed by SupunS** 2017-11-17 08:30 UTC
Labels: Type/Bug
